name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: transformers.js
      path_to_docs: transformers.js/docs
      pre_command: cd transformers.js && npm install && npm run docs-api
      additional_args: --not_python_module
