name: Unit tests

on:
  push:
    branches: [ main, docs ]
  pull_request:
    branches: [ main, docs ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: pip install -r scripts/requirements.txt
      - run: npm run generate-tests
      - run: npm run test
